; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2 on Tue Aug 06 2019 23:15:45 GMT+0200 (Central European Summer Time)


M83            ; relative extruder moves
G1 E-3 F3000  ; retract 3mm of filament
G91 ; Relative Positioning
G1 Z10 F360; Raise Z
M104 S0     ; turn off temperature
M140 S0     ; turn off heatbed
M107        ; turn off fan